# Generated by Django 4.0 on 2022-03-02 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_name', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='rateing',
        ),
        migrations.AlterField(
            model_name='album',
            name='num_stars',
            field=models.IntegerField(choices=[(1, 'Worst'), (2, 'Bad'), (3, 'Not Bad'), (4, 'Good'), (5, 'Excellent!')]),
        ),
    ]
